#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════
# VPN Lab Setup Script
#
# Generates all WireGuard and SSH keys needed by the local VPN lab.
# Run once before starting the docker-compose environment.
#
# Usage:
#   bash test/vpn-lab/setup.sh
#
# What it creates:
#   test/vpn-lab/server.key          WireGuard server private key
#   test/vpn-lab/server.pub          WireGuard server public key
#   test/vpn-lab/client.key          WireGuard client private key
#   test/vpn-lab/client.pub          WireGuard client public key
#   test/vpn-lab/wg0-server.conf     WireGuard server config (mounted into vpn-server)
#   test/vpn/wg0.conf                WireGuard client config (mounted into vpn sidecar)
#   test/secrets/ssh-private-key     SSH private key for Ansible
#   test/secrets/ssh-public-key      SSH public key (mounted into remote-host)
#
# All generated files are git-ignored (see .gitignore).
# ══════════════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

VPN_LAB_DIR="${SCRIPT_DIR}"
SECRETS_DIR="${REPO_ROOT}/test/secrets"
CLIENT_WG_CONF="${REPO_ROOT}/test/vpn/wg0.conf"

# ── Network constants (must match docker-compose networks) ─────────
WG_SERVER_IP="10.10.99.1"
WG_CLIENT_IP="10.10.99.2"
WG_LISTEN_PORT="51820"
WG_VPN_SUBNET="10.10.99.0/24"
BACKEND_SUBNET="10.10.20.0/24"   # subnet where remote-host lives

log() { echo "[SETUP] $*"; }
err() { echo "[SETUP][ERROR] $*" >&2; exit 1; }

# ── WireGuard key generation ───────────────────────────────────────
# Uses the local 'wg' tool if available, otherwise falls back to Docker.
_wg_genkey() {
  if command -v wg &>/dev/null; then
    wg genkey
  else
    # Redirect ALL apt-get output to /dev/null so only the key reaches stdout
    docker run --rm debian:bookworm-slim bash -c \
      "apt-get update -qq >/dev/null 2>&1 && apt-get install -y -qq --no-install-recommends wireguard-tools >/dev/null 2>&1 && wg genkey"
  fi
}

_wg_pubkey() {
  local privkey="$1"
  if command -v wg &>/dev/null; then
    echo "${privkey}" | wg pubkey
  else
    echo "${privkey}" | docker run --rm -i debian:bookworm-slim bash -c \
      "apt-get update -qq >/dev/null 2>&1 && apt-get install -y -qq --no-install-recommends wireguard-tools >/dev/null 2>&1 && wg pubkey"
  fi
}

generate_wg_keypair() {
  local name="$1"
  local priv="${VPN_LAB_DIR}/${name}.key"
  local pub="${VPN_LAB_DIR}/${name}.pub"

  if [[ -f "${priv}" && -f "${pub}" ]]; then
    log "WireGuard keys for '${name}' already exist — skipping."
    return
  fi

  log "Generating WireGuard keypair for '${name}'..."
  local privkey
  privkey="$(_wg_genkey)"
  echo "${privkey}" > "${priv}"
  chmod 600 "${priv}"
  _wg_pubkey "${privkey}" > "${pub}"
  log "  ${priv}"
  log "  ${pub}"
}

# ── WireGuard server config ────────────────────────────────────────
write_server_conf() {
  local out="${VPN_LAB_DIR}/wg0-server.conf"
  local server_priv client_pub

  server_priv="$(cat "${VPN_LAB_DIR}/server.key")"
  client_pub="$(cat "${VPN_LAB_DIR}/client.pub")"

  cat > "${out}" <<EOF
# ══════════════════════════════════════════════════════════════════
# WireGuard Server Config — TEST LAB ONLY
# Auto-generated by test/vpn-lab/setup.sh — do NOT commit
# ══════════════════════════════════════════════════════════════════
[Interface]
PrivateKey = ${server_priv}
Address    = ${WG_SERVER_IP}/24
ListenPort = ${WG_LISTEN_PORT}

# Forward VPN traffic into the backend network (where remote-host lives).
# Uses MASQUERADE so remote-host replies route back correctly.
# Note: multiple PostUp/PostDown entries instead of \ continuation — wg-quick
# parses line-by-line and does not support backslash continuation.
PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp   = iptables -A FORWARD -o wg0 -m state --state RELATED,ESTABLISHED -j ACCEPT
PostUp   = iptables -t nat -A POSTROUTING -s ${WG_VPN_SUBNET} ! -o wg0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -o wg0 -m state --state RELATED,ESTABLISHED -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -s ${WG_VPN_SUBNET} ! -o wg0 -j MASQUERADE

[Peer]
# Ansible Job WireGuard client (sidecar)
PublicKey  = ${client_pub}
AllowedIPs = ${WG_CLIENT_IP}/32
EOF

  chmod 600 "${out}"
  log "Server config: ${out}"
}

# ── WireGuard client config ────────────────────────────────────────
write_client_conf() {
  local client_priv server_pub

  client_priv="$(cat "${VPN_LAB_DIR}/client.key")"
  server_pub="$(cat "${VPN_LAB_DIR}/server.pub")"

  cat > "${CLIENT_WG_CONF}" <<EOF
# ══════════════════════════════════════════════════════════════════
# WireGuard Client Config — TEST LAB (auto-generated)
# Auto-generated by test/vpn-lab/setup.sh — do NOT commit
# ══════════════════════════════════════════════════════════════════
[Interface]
PrivateKey = ${client_priv}
Address    = ${WG_CLIENT_IP}/24

[Peer]
PublicKey           = ${server_pub}
# "vpn-server" resolves via Docker internal DNS when both containers
# share the same Docker network (vpn-net).
Endpoint            = vpn-server:${WG_LISTEN_PORT}
AllowedIPs          = ${WG_VPN_SUBNET}, ${BACKEND_SUBNET}
PersistentKeepalive = 25
EOF

  chmod 600 "${CLIENT_WG_CONF}"
  log "Client config: ${CLIENT_WG_CONF}"
}

# ── SSH keypair ────────────────────────────────────────────────────
generate_ssh_keys() {
  local priv="${SECRETS_DIR}/ssh-private-key"
  local pub="${SECRETS_DIR}/ssh-public-key"

  if [[ -f "${priv}" ]] && grep -qE 'BEGIN (OPENSSH|RSA|EC) PRIVATE KEY' "${priv}" 2>/dev/null; then
    log "SSH keys already exist — skipping."
    # Ensure the public key companion file exists
    if [[ ! -f "${pub}" ]]; then
      ssh-keygen -y -f "${priv}" > "${pub}"
      log "  Regenerated companion public key: ${pub}"
    fi
    return
  fi

  log "Generating SSH keypair for Ansible..."
  ssh-keygen -t ed25519 -f "${priv}" -N "" -C "ansible-job-vpn-lab" -q
  mv "${priv}.pub" "${pub}"
  chmod 600 "${priv}"
  chmod 644 "${pub}"
  log "  ${priv}"
  log "  ${pub}"
}

# ── Main ───────────────────────────────────────────────────────────
main() {
  log "=== VPN Lab Setup ==="
  log "Repo root: ${REPO_ROOT}"
  echo ""

  mkdir -p "${VPN_LAB_DIR}" "${SECRETS_DIR}"

  generate_wg_keypair "server"
  generate_wg_keypair "client"
  write_server_conf
  write_client_conf
  generate_ssh_keys

  echo ""
  log "=== Done ==="
  echo ""
  echo "  Start the standalone VPN lab (for testing from K8s dev):"
  echo "    docker compose -f docker-compose.vpn-lab.yml up -d"
  echo ""
  echo "  Start the full local stack (VPN lab + Ansible executor):"
  echo "    SKIP_VPN=false docker compose --profile vpn-lab up"
  echo ""
}

main "$@"
