---
environment: staging
timezone: Europe/Madrid

vpn_subnet: "10.20.0.0/24"
vpn_interface: wg0

ansible_ssh_private_key_file: /run/secrets/ssh-private-key

app_port: 8080
app_version: "{{ lookup('env', 'APP_VERSION') | default('stable', true) }}"

log_level: info
